return {
	LibraryRemoteUrl = "https://raw.githubusercontent.com/sametexe001/sametlibs/refs/heads/main/Mentality/Library.lua",
	DisplayName = "kpop demon",
	Races = {
		Race1 = { Name = "City Highway Race", Map = "Tokyo" },
		Race2 = { Name = "Rainbow Bridge Sprint", Map = "Tokyo" },
		Race3 = { Name = "Doro Sprint", Map = "Tokyo" },
		Race4 = { Name = "Rainbow Rinkai Doro Sprint", Map = "Tokyo" },
		Race5 = { Name = "Interstate 80 Sprint", Map = "Boneville" },
		Race6 = { Name = "Cross-Country Sprint", Map = "Boneville" },
		Race7 = { Name = "Salt Flats Drag", Map = "Boneville" },
		Race8 = { Name = "Salt Flats Grand Prix", Map = "Boneville" },
		Race9 = { Name = "Salt Flats MotoGP", Map = "Boneville" },
	},
	TeleportCooldownSeconds = 5,
	SpeedMultiplierDefault = 1,
	SpeedMultiplierStep = 0.05,
	SpeedMultiplierMin = 0.5,
	SpeedMultiplierMax = 1000,
	ApplySpeedMultiplierToChassisTune = true,
	SteeringSensitivityDefault = 1,
	SteeringSensitivityMin = 0.25,
	SteeringSensitivityMax = 1000,
	ApplySteeringTune = true,
	SoloQueueCooldownSeconds = 3,
	AllowClientAutomation = true,
	RequireStudioForAutomation = false,
	TeleportEverySeconds = 2.5,
	TeleportEverySecondsMin = 0.35,
	TeleportEverySecondsMax = 45,
	TeleportChainInterval = 2.5,
	CheckpointDwellSeconds = 2.5,
	AutoDriveV1SteerPulse = 0.08,
	AutoDriveV2SteerPulse = 0.04,
	AutoDriveMinThrottleDistance = 40,
	CheckpointSnapYOffset = 3,
	UseClientCheckpointSnap = true,
	ZeroVelocityAfterCheckpointSnap = true,
	CarFlySpeed = 160,
	CarFlySpeedMin = 20,
	CarFlySpeedMax = 500,
	CarFlyVelocityCap = 8000,
	TuneReapplyIntervalSeconds = 0.12,
}